Delete duplicate gifs and add new gif
kaamelott-gifboard/kaamelott-gifboard pull request #46
Opened 2021-07-16 15:34 UTC by leghort

2021-07-19 07:18 UTC, VinceTommasi commented
Merci @leghort :pray:

2021-07-19 07:24 UTC, VinceTommasi requested changes

2021-07-19 07:24 UTC, VinceTommasi commented on gifs.json
> +    },
@leghort Peux-tu retirer la dernière virgule? Elle rend le json invalide. Merci! :pray:

2021-07-21 03:03 UTC, leghort commented on gifs.json
> +    },
C'est fait

2021-07-21 06:52 UTC, VinceTommasi approved these changes

2021-07-21 06:52 UTC, merged

2021-07-21 06:52 UTC, VinceTommasi commented
Merci pour ta contribution @leghort !

2021-07-21 06:53 UTC, VinceTommasi commented
https://kaamelott-gifboard.fr/gif/oui-bah-non